#!/usr/bin/env ruby

require 'optparse'

vopts = %w[ca cert dh extra-certs key pkcs12 secret crl-verify
           http-proxy-user-pass tls-auth tls-crypt]

opt = {}
OptionParser.new do |opts|
  opts.on('--conf CONF') { |c| opt[:conf] = c }
  vopts.each do |vo|
    opts.on("--#{vo} #{vo}") { |o| opt[vo] = o }
  end
end.parse!
abort('need conf') unless opt[:conf]

inl = {}
File.readlines(opt[:conf]).each do |l|
  next if /^($|#)/ =~ l

  k, v, suff = l.split
  puts "key-direction #{suff}" if k == 'tls-auth' && suff
  if vopts.include?(k)
    inl[k] = v
  else
    puts l
  end
end

opt.each_pair { |k, v| inl[k] = v unless k == :conf }

inl.each_pair do |k, v|
  conf_dir = File.dirname opt[:conf]
  c = if File.exist?(v)
        File.read v
      elsif File.exist?("#{conf_dir}/#{v}")
        File.read "#{conf_dir}/#{v}"
      else
        "#{v}\n"
      end
  puts "<#{k}>\n#{c}</#{k}>"
end
